services:
  - type: web
    name: appbarber-server
    env: node
    rootDir: server
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    plan: free
    region: oregon
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: WHATSAPP_API_URL
        sync: false
      - key: WHATSAPP_API_TOKEN
        sync: false
      - key: WHATSAPP_INSTANCE_NAME
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        value: re_ZyLeoAXN_957RG3K7ijmKeQ7skrezz7zN
      - key: EMAIL_FROM
        value: '"Next App" <nao-responda@corteconexao.com.br>'
      - key: FRONTEND_URL
        sync: false
